# Generated by Django 5.2 on 2025-04-07 04:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('IN', 'Inkomen'), ('FLEX', 'Flexibele lasten'), ('VAST', 'Vaste lasten')], max_length=4)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
